version: '3.8'

services:
  app:
    image : ghcr.io/lukekoko/memeapi:latest
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - memeapi
    environment:
      - JAVA_OPTS=-Xmx512M -Xms256M -XX:MaxDirectMemorySize=512M
      - JAVA_TOOL_OPTIONS=-Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64 -Xmx64M

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - memeapi

volumes:
  redis:
  redis-config:

networks:
  memeapi: