version: '3.8'

services:
  app:
    image : ghcr.io/lukekoko/memeapi:release
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - app

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - app

volumes:
  redis:
  redis-config:

networks:
  app: