reddit:
  clientId:
  clientSecret:
  userAgent: SpringMemeApi
  url: "https://www.reddit.com/api/v1/access_token"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: memeapi
      jakarta:
        persistence:
          create-database-schemas: true
logging:
  level:
    root: info

