reddit:
  clientId:
  clientSecret:
  userAgent: api:com.lukekoko.memeapi:v0.0.1
  url: "https://www.reddit.com/api/v1/access_token"

spring:
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      timeout: 60000
  docker:
    compose:
      enabled: true

logging:
  level:
    root: info

