name: CI

on:
  push:
    branches:
      - "deploy"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build image
        run: ./mvnw clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build-Tag-Push my-app
        run: |
          ./mvnw spring-boot:build-image
          docker tag memeapi:0.0.1-SNAPSHOT memeapi:latest
          docker push ${{env.REGISTRY}}/lukekoko/memeapi:latest